$ANSIBLE_VAULT;1.1;AES256
30323336323931333234623730316562376166306135616664656364396531643065396637313533
6532303165343233356230626131393130653164323239300a373639326439386334343161616164
62663431366437363236326433653064366365383433663730346266333836366634333264663033
3964353336383366340a633035343539353434366432383237643434343032353937633733376135
34373831616436316163626566386631333365653234313534303237383533656363326366613336
63393130326132323663316562366264313033386363663531623161646336313133386633363263
64613865633465653265626365663838353731613263323465653535613439373131316135333534
33343539363236363833346561326431313062393264333163373030393935623731383131656266
62356337333536353563356566366164633131386261363865396530313235343738376561373834
32303666373062336134653130306231306264376634663332376361666165363631613961396331
33316533643163636430323335313965613061636239383732333030396636646230366238393462
65363961666663323165356634323336623935303037353939396466303061636433343231313866
37313534343737323662663464396531663133383863333532663130623563336137393336303563
62306664663465353562616564303530666663656664396139386533323666353137653033323930
36356534666339386661636538323265303530373332653335316364316663363530353034343165
33653136313335303835316336323133313937393731663438346134333736383364333764346637
35383433376432656465303435623361313536383265626334643233653263646463656336393435
63313566613238326330323066623636383063396666363338366334343431623039323232643132
33326138316236616265333565343935656632666636343863326334366532313430316462323839
31356166643362366264643536633462313438656531653536336563643563336138643837643562
3939
