# playbooks/site.yml
#
# "Site" entrypoint that composes the core operational playbooks.
# Run with tags/skip-tags or --limit to narrow scope.
#
# Examples:
#   ansible-playbook playbooks/site.yml --ask-become-pass
#   ansible-playbook playbooks/site.yml --tags users --vault-password-file .secrets/vault_pass.txt --ask-become-pass
#   ansible-playbook playbooks/site.yml --skip-tags docker
#
- import_playbook: base.yml
- import_playbook: gpu_check.yml
- import_playbook: users.yml
- import_playbook: hosts.yml
- import_playbook: docker.yml
- import_playbook: tailscale.yml
